# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: <%= ENV["domain_name"] %>
  secret_key_base: 1e203c0b06398218b5b6c71fea26494847b17ce05fc654786e4a154bb198549a1e2a55e378c19ca2c19a7be7ee08890d95a37f6b11faaaa646474fc001fa6383

test:
  domain_name: example.com 
  secret_key_base: d18802856f553246e24ee7f921a7ea50ba9aae02f0c02b8ccf4c10a89334b334dc93348d2731b339d0f2f93023ac87e13eaf5441dd7884d72cb3b9f68748f5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["domain_name"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
